### ISSUE TITLE
Sharing device is not projecting sucessful message after sharing a VC

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#238] opened 2022-11-09 13:52 UTC
**Describe the bug**
Sharing device is not projectig sucssefull message after sharing a VC

**To Reproduce**
Device A --> Requesting
Device B --> Sharing

1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. Connection is established, Now select VC and click on share
5. From device A accept the request, the VC will be shared successefully

**Expected behavior**
The device B should project a message for the successfull sharing

**Observed behavior**
After successfully VC sharing the device B going to home page. without any message of the sharing

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/actions/runs/3287270987

**Comment by Sujithbn** [comment] 2022-12-21 08:15
@santhoshsunder Could you please verify this in latest build and confirm as we are unable to reproduce this issue.

**Comment by damodarguru** [comment] 2023-03-16 10:25
Verified this issue in qa-1201-b2 environment, issue is not occurring. After sharing VC, we getting successful message in both devices. I am attaching the screenshot and the device details below for reference. Hence closing the bug.
Screenshots: -
![image](https://user-images.githubusercontent.com/124761463/225586650-7abe6184-f732-4fc6-a291-f75f9ca2c88d.png)
![image](https://user-images.githubusercontent.com/124761463/225586805-6738de08-daae-432b-b232-fbd26f40e7ca.png)
![image](https://user-images.githubusercontent.com/124761463/225586873-0fb18cab-4b23-4a7b-bb23-a827e4a96cef.png)
![image](https://user-images.githubusercontent.com/124761463/225586929-40ce4184-cc35-42f2-b96c-5c4cff986681.png)
![image](https://user-images.githubusercontent.com/124761463/225587024-1b646ee2-6529-4c70-9c71-5a25dd0f59cb.png)
![image](https://user-images.githubusercontent.com/124761463/225587534-6bb0b7bf-fcab-41ee-aa0f-c2c0eb9927bf.png)
Tested In: -
Device A: Redmi 7A
Android Version: 10
BLE version :4.2
Inji app link: https://github.com/mosip/inji/actions/runs/4376878070

Device B: Redmi 6A
Android Version: 9
BLE version :4.2
Inji app link: https://github.com/mosip/inji/actions/runs/4376897206
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Closed as completed** 2023-03-16 12:45 UTC
Labels: bug, triage, Minor, beta_must_fix
