### ISSUE TITLE
Camera permission not requested in iPhone

### ISSUE THREAD

**Issue by shreeThaanuTw** [mosip/inji#502] opened 2023-01-27 11:51 UTC
**Describe the bug**
When a Camera is used in iPhone, a permission to use iPhone Camera must be popped up requesting user whether or not use the camera.

**To Reproduce**

1. Go to scan tab, accept bluetooth permission
2. Click on home, Add a ID
3. Again try to go to scan app, it shows empty screen.
4. At this point the camera usage must be shown, but it isn't.

**Expected behavior**
when opening scan tab, The camera usage must be shown, but it isn't.

**Screenshots**
If applicable, add screenshots to help
![IMG_7577](https://user-images.githubusercontent.com/83670437/215079721-d2d911de-e72a-47f6-bc1b-ab1ab9e28a80.PNG)
 explain your problem.

**Smartphone (please complete the following information):**

- Device: iPhone 12 pro
- OS: iOS 16.0
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: https://api.collab.mosip.net

**Additional context**

**Comment by santhoshsunder** [comment] 2023-03-21 06:38
Tested that issue, the issue is not observed anymore, the app is asking for camera permission as expected, adding the screenshot and device details below, and closing this bug 

Screenshot : 
https://user-images.githubusercontent.com/102220709/226533899-c364d18c-6be4-4f84-a7ff-9ae4af45bbe3.mp4

Tested on : 
Device: iPhone 11
OS: 15.4.1
Inji app version: 0.4.1 (29) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Closed by santhoshsunder** 2023-03-21 06:38 UTC
Labels: bug, triage, iOS, Critical, P2
