### ISSUE TITLE
Android - face auth is not recognising resident face 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#524] opened 2023-02-01 13:17 UTC
**Describe the bug**
Face auth is not recognising resident face in specific device (device details where added below)

**To Reproduce**
Tested all three face authentication scenario, all the three scenarios where listed below

1. Sharing VC via face authentication in receivers end 
2. Sharing VC via face authentication in resident end
3. Face authentication while IDP QR code login

**Expected behavior**
App should recognise the resident face and allow the scenario successfully

**Observed**
The app is not recognising the residents face, so we are blocked in QR code IDP login and failing in sharing scenarios with face auth, on only specific device (device details where added below)

**Screenshots**
https://user-images.githubusercontent.com/102220709/216053043-1a4400b4-e9cc-4551-8491-c51888f4bf4a.mp4

**Smartphone :**
- Device: Redmi K20 pro
- OS: Android 11
- BLE version: 5.0
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/4062244892

**Additional context**
Other than all testing device this device contain pop camera

**Comment by rakhimosip** [comment] 2023-02-01 16:36
@santhoshsunder this looks similar to https://github.com/mosip/inji/issues/434 that we triaged today.  Can you please confirm?

**Comment by lsivanand** [comment] 2023-02-03 06:47
@MonobikashDas as Santosh observed this issue on the correct build, as he couldn't reproduce it now, we should reduce the priority and guide him what data you need from him when he faces the issue again,

**Comment by rakhimosip** [comment] 2023-02-03 10:26
Refer to notes https://github.com/mosip/inji/issues/434#issuecomment-1415624199

**Comment by Sujithbn** [comment] 2023-02-10 11:26
@MonobikashDas Once 434 is fixed, please retest and confirm.

**Comment by Anuranjan14** [comment] 2023-03-13 13:38
Face auth is not working in below devices. Hence re-opening

https://user-images.githubusercontent.com/120705365/224717887-70eb8c91-307f-452e-b291-81422b0120a3.mp4

Device details:-
Verifier:
Device: Redmi 7A
OS: Android 10
BLE version: 4.2
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

Wallet:
Device: Redmi K20 pro
OS: Android 11
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

CommitId:
![image](https://user-images.githubusercontent.com/120705365/224713274-717b4826-e88c-4e2e-bca6-fe0e0f9e40f1.png)
![image](https://user-images.githubusercontent.com/120705365/224713317-8a94c746-248a-48ae-9a5f-7775ae5a4571.png)

**Comment by Pragya279** [comment] 2023-04-04 08:55
This bug has been moved to Jira.
Link to Jira bug: https://mosip.atlassian.net/browse/MOSIP-26843

**Comment by Raginikrishnamurthy** [comment] 2023-10-10 14:09
Issue verified and closed in jira https://mosip.atlassian.net/browse/INJI-40, hence closing on github.

**Closed by Raginikrishnamurthy** 2023-10-10 14:09 UTC
Labels: bug, Critical, triaged, BLE, MEC, face auth, HotFix, moved-to-jira
