### ISSUE TITLE
[Translation] Translate text to other languages for "Powered by BLE"

### ISSUE THREAD

**Issue by ravikp** [mosip/inji#499] opened 2023-01-27 07:55 UTC
Summary: The mode of VC transport (GNB/BLE) is given as an indication in the Profile screen. The text `Powered by BLE` and `Powered by GoogleNearby` requires translation to other languages. This change is required till both the features are enabled at the runtime.

This text serves a purpose of identifying the transport mechanism whether it is built for google nearby or ble.

**Comment by rakhimosip** [comment] 2023-01-27 14:20
@Anushree09-N @santhoshsunder please take up this task to translate the BLE related labels into other languages.

**Comment by Sujithbn** [comment] 2023-03-15 10:03
@Anushree09-N : Please verify and close it today

**Comment by ravikp** [comment] 2023-03-15 10:05
The text is added in the commit - 2bda45619be74250a695a66cc760a1aa3ac1cb87

And the feature itself removed in the latest as of ed206c9a80e9745a3a19ee457bec29a00cf7892a

**Comment by santhoshsunder** [comment] 2023-03-15 13:02
tested this task in the new build, we are seeing the "powered by BLE" in the settings page in both platforms, attaching the screenshot and device details below,

screenshot : 
![image](https://user-images.githubusercontent.com/102220709/225310189-0e0571fc-6db2-4127-81bd-ebf741f001bd.png)
![image](https://user-images.githubusercontent.com/102220709/225315450-ad58ee2c-866b-4af8-aa39-3025536a8836.png)

Tested on : 
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP server : mec.mosip.net
APP link : https://github.com/mosip/inji/actions/runs/4376878070
Testflight : 0.4.0 (27)

**Comment by Raginikrishnamurthy** [comment] 2023-03-17 09:45
This feature is intended to be removed in the latest build. Hence, no activity from qa team.

**Comment by Sujithbn** [comment] 2023-03-17 10:43
@ravikp Please close the task if this feature is intended to be removed in the latest build

**Comment by ravikp** [comment] 2023-03-21 05:54
This issue is not applicable as we are going to have an about section.

**Comment by Alka1703** [comment] 2023-04-21 06:47
The `Powered by BLE` text is no longer displayed on the Profile/Settings screen. So the issue is no more valid.

**Closed** 2023-04-21 06:47 UTC
Labels: task, triaged, beta_must_fix, BLE, BLE-Sharing
