### ISSUE TITLE
Cross platform : Sharing is not working even after establishing a connection

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#543] opened 2023-02-08 06:46 UTC
Describe the bug
unable to share VC
  - Wallet stuck in sharing state
  - Verifier stuck in "connected waiting for ID" state

**To Reproduce**
**Prerequisite:**

iOS (wallet) --> VC is downloaded and stored
Android (verifier)

**steps:**

1. Scan the qr code from iOS
2. select VC to share
3. click on "Accept request and choose ID" button

**Current behavior**
Device stucks in sharing and receiving state 

https://user-images.githubusercontent.com/79500509/217312790-29e393bd-f860-475f-86bf-3b3ff2dd04ce.mp4

Expected behavior
VC sharing should be successful

Android App version: 
![image](https://user-images.githubusercontent.com/79500509/217445412-02f4094e-62b0-42dc-b85a-e982712b919a.png)

Smartphone (please complete the following information):

Verified in:

wallet
Device: iPhone 7
OS: 15.6
Inji app version: 0.4.1 (15) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

verifier
Device: Redmi 7A
OS: Android 10
Inji app version : https://github.com/mosip/inji/actions/runs/4062244892
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

**Comment by santhoshsunder** [comment] 2023-02-09 06:09
verified this issue in the new app, on both IOS and android, and was able to replicate the same issue again in a specific set of devices, I am adding the details of the devices and adding the screenshot bellow 

**Screenshot:**
![photo_6278393845267936395_y](https://user-images.githubusercontent.com/102220709/217731397-980c8a12-8f01-4e26-a35f-1fb6950fdc7b.jpg)

Uploading document_6278393844811696179.mp4…

**Verified in:**
wallet -
Device: iPhone 8
OS: 16
Inji app version: 0.4.1 (15) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

verifier
Device: Redmi 7A
OS: Android 10
Inji app version : https://github.com/mosip/inji/actions/runs/4123991786
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

**Comment by rakhimosip** [comment] 2023-02-15 07:59
**Tested on** 
iOS(Wallet) - iPhone 14 Promax
Android (Verifier) - Redmi 9i sport

**Commit ID:** https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12

We were able to execute this test case successfully.

**Comment by rakhimosip** [comment] 2023-02-15 08:04
@krishnakumar4a4  to add root cause

**Comment by krishnakumar4a4** [comment] 2023-02-15 09:57
The issue seems to happen when the MTU negotiation between the above devices happened at 185 while the chunk transfer was happening at 512. In the latest release https://github.com/mosip/inji/commit/5fa5c9b3fa97c3492a5cf5eb709a60ae5703ba12 , we have added dynamic MTU negotiation between IOS to Android. It should address the transfer issue. 

Addressed with #409

**Comment by Anushree09-N** [comment] 2023-02-20 14:25
Able to replicate the issue in below set of combinations :

Verifier:
Device: Redmi k20 pro
OS : Android 11
BLE 5.0

Wallet
Device: iphone 11
OS: iPhone 15
Inji app version: 0.4.1 (18) -> Testflight
BLE 5.0

Observed:

Failed to share VC in the 3rd attempt.
Failed to share VC in 4th attempt .after restarting the verifier app
Version
image

image

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

Verifier:
Device: Redmi 6A
OS : Android 9
BLE 4.2

Wallet
Device: iphone 7
OS: iphone 15.6
Inji app version: 0.4.1 (18) -> Testflight
BLE 4.2

Observed:

VC share failed in 2nd attempt . Wallet displayed "ID has been sent". Verifier displayed "Connected to the device waiting
for ID".
VC share failed in 1st attempt after restarting verifier app
Version
image

image

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
App Link: https://mosip-team.slack.com/files/U04KHL40S3X/F04QEC4SCQY/io.mosip.residentapp-0.2.1-858-5fa5c9b-develop-dirty-mosip_20230215_1516_universal.apk

**Comment by Alka1703** [comment] 2023-02-24 13:49
This issue was due to transfer report getting stuck during the VC transfer. After adding the fix for iOS duplicate events, we observed that the issue is no longer reproducible on our devices(it was reproducible earlier).

PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/26
PR for mosip/inji:https://github.com/mosip/inji/pull/584

The PRs have been merged in 24-02-2023 Release and the latest commit id on mosip/inji/develop is cb47493

**Comment by Anushree09-N** [comment] 2023-03-07 13:38
Verified in: 
-----------------------------------------------------------------
1. 
wallet
Device: iPhone 7
OS: 15.6
Inji app version: 0.4.1 (23) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

verifier
Device: Redmi 7A
OS: Android 10
Inji app version : https://github.com/mosip/inji/actions/runs/4343056712
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

Observation: VC sharing was successfully for multiple attempts.
---------------------------------------------------------------------------------
2.
wallet -
Device: iPhone 8
OS: 16
Inji app version: 0.4.1 (23) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

verifier
Device: Redmi 7A
OS: Android 10
Inji app version : https://github.com/mosip/inji/actions/runs/4343056712
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 4.2

Observation:
1. Crashing issue occured 
![image](https://user-images.githubusercontent.com/79500509/223436908-77ba2cf7-cf80-493b-aa2e-4d79a471feef.png)

2. Both device displayed disconnect message
![image](https://user-images.githubusercontent.com/79500509/223436999-a0b78190-fb18-4eb1-a596-ee6551a2d0b7.png)
--------------------------------------------------------------------------------------
3.
Verifier:
Device: Redmi k20 pro
OS : Android 11
BLE 5.0
App link: https://github.com/mosip/inji/actions/runs/4343056712

Wallet
Device: iphone 11
OS: iPhone 15
Inji app version: 0.4.1 (23) -> Testflight
BLE 5.0

Observation: VC sharing was successfully for multiple attempts.
-------------------------------------------------------------------------------------
4.
Verifier:
Device: Redmi 6A
OS : Android 9
BLE 4.2
App link: https://github.com/mosip/inji/actions/runs/4343056712

Wallet
Device: iphone 7
OS: iphone 15.6
Inji app version: 0.4.1 (18) -> Testflight
BLE 4.2

Observation: VC sharing was successfully for multiple attempts.
-----------------------------------------------------------------------------------------
Commit id:
![image](https://user-images.githubusercontent.com/79500509/223438176-d3cb55cf-4ea5-4d60-a7a1-666211c639d9.png)

![image](https://user-images.githubusercontent.com/79500509/223438767-01ad8381-4de3-42b7-bed3-dcb30c81611c.png)

**Closed** 2023-03-13 10:09 UTC
Labels: bug, triage, blocker, BLE, BLE-Sharing
