### ISSUE TITLE
Android - Unable to login into idp portal sucessfully 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#505] opened 2023-01-30 10:43 UTC
**Describe the bug**
Unable to login into idp portal from QR code login

**To Reproduce**
Prerequiste: one VC should be downloaded and binded, have idp compatable login with qr portal ready

1. Authenticate app and get into it
2. Go to scanner page
3. Scan the IDP portal QR code log-in
4. select the binded UIN and perform the authentication method
5. select the requird atributes on the consent page
6. and click continue 

**Expected behavior**
We should able to login in successfully with out any errors

**Observed**
We unable to login and getting error as "IDA-MLC-015" as shown in the below screen shot

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/215455403-60d089fe-17bb-4400-a6c2-0a12aeb888d8.png)

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.net
- APP link; https://github.com/mosip/inji/actions/runs/3986424542

**Comment by Sujithbn** [comment] 2023-01-30 11:43
@santhoshsunder As discussed on call, unable to reproduce this issue. Let us know if you identify any patterns.

**Comment by Anuranjan14** [comment] 2023-03-13 11:46
Verified this issue and its working as expected ie user is able to login into e-signet portal successfully.Hence closing.
Adding video and device details for the reference.

https://user-images.githubusercontent.com/120705365/224692809-d9341ef5-a8eb-48e6-8ecd-1128c8c31ca4.mp4

Device details :
Device: Redmi K20 pro
OS: Android 11
BLE version: 5.0
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
app link: https://github.com/mosip/inji/actions/runs/4376897206

CommitId:
![image](https://user-images.githubusercontent.com/120705365/224692928-30b43bb3-b5bf-485f-9fb9-70ea5c13645d.png)
![image](https://user-images.githubusercontent.com/120705365/224693000-d2464f0b-28cc-4e1c-94ea-f6803597ff82.png)

**Closed** 2023-03-14 12:55 UTC
Labels: bug, triage, Critical, BLE
