### ISSUE TITLE
Unable to get UIN/VID using AID 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#185] opened 2022-10-28 10:12 UTC
**Describe the bug**
Unable to get UIN/VID using AID

**To Reproduce**
1. Unlock the app
2. click on ADD ID button in home page
3. click on "Don't have your UIN/VID? Get it here " link.
4. Enter AID
5. click on Get UIN/VID button

**Current behavior**
User still remains in AID screen without moving navigating to Otp screen

**Expected behavior**
When user clicks on Get UIN/VID button by entering AID number should prompt to enter Otp, After successful Otp match UIN should be auto filled. 

**Screenshots**

https://user-images.githubusercontent.com/79500509/198562746-0e6b9e6c-2cf2-40bd-81cc-37c1d5c17c0f.MP4

**Smartphone (please complete the following information):**
- Device: iPhone XR
- OS: 15.4.1
- Inji app version: iOS 0.4.0 (16)-> In Test flight
- MOSIP Version: 1.2.1
- MOSIP server: qa-121.mosip.net

**Comment by adityankannan-tw** [comment] 2023-03-24 09:08
This issue was happening because IOS does not support multiple modal loading one over another. This has been fixed.

https://user-images.githubusercontent.com/109274996/227442886-fd5edf92-53a9-4c4f-ae6d-b90db3e0eaaa.mov

**Comment by santhoshsunder** [comment] 2023-03-28 05:59
Verified this issue in the new build, and the issue is not observed, we are able to download VC from AID, hence closing this bug

Screenshot : 
https://user-images.githubusercontent.com/102220709/228142182-5c1c49bd-c889-48c0-8f8f-b227c174cf94.mp4

Tested on :
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Closed by santhoshsunder** 2023-03-28 05:59 UTC
Labels: bug, blocker, triaged, beta_must_fix
