### ISSUE TITLE
Reason for sharing is not displayed when received identical VC with different reason for sharing. 

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#101] opened 2022-09-08 08:01 UTC
**Describe the bug**

**To Reproduce**
Prerequisite device A (requesting): Bluetooth enabled
Prerequisite device B (sharing): Bluetooth, location and camera access: enabled
1. Share VC from device B to device A with reason for sharing verify that it is displayed under ""Received VIDs""
2. Share same VC from device B to device A a second time with reason for sharing verify that only one VC is displayed under ""Received VIDs""
3. Under Received VID view VC 

**Current behavior**
Displayed only one "reason for sharing" instead for 2.

**Expected behavior**
single VC should have 2 Reason for sharing. 

**Screenshots**
![Screenshot_2022-09-08-13-28-20-84_fba87592218da393460b8e128d2f49dd (1)](https://user-images.githubusercontent.com/79500509/191174248-efeb3c84-3092-4b3e-8c35-3187cc532b7b.jpg)

**Smartphone (please complete the following information):**

- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: 1.2.0.1
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
Env: qa5.mosip.net

**Comment by Anil-kumar-Majji** [comment] 2022-10-03 06:09
When I tried replicating this issue, the bug mentioned above was already rectified. The reasons for sharing are displayed when receiving identical VC with different reasons for sharing.

**Comment by Sujithbn** [comment] 2022-11-07 11:19
This issue needs to be reverified in the latest build and confirm us.

**Comment by santhoshsunder** [comment] 2022-11-16 11:50
Tested this issue in QA-121 env, the issue is not observed any more, hense closing this bug

**Closed by santhoshsunder** 2022-11-16 11:50 UTC
Labels: bug, triaged, Retest
