### ISSUE TITLE
MOSIP logo trimed in VC card

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#142] opened 2022-10-03 13:30 UTC
**Describe the bug**
MOSIP logo got trimed in both VC's preview in home page and VC details page

**To Reproduce**
1. Open app and head to home page
2. click on add ID and download VC
3. Go back to home 

**Expected behavior**
The mosip logo should placed fully and properly aligned with the structure

**Current behavior**
MOSIP logo got trimed in both VC's preview in home page and VC details page

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/193590002-d5c70153-e003-47eb-a025-c0fcc7c9d92b.png)
![image](https://user-images.githubusercontent.com/102220709/193590036-e909b831-8074-4ced-addd-7891edf47411.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net

**Comment by damodarguru** [comment] 2023-03-24 05:49
Verified this issue in qa-1201-b2 environment, the issue is fixed, we are getting full logo of MOSIP in VC card, I am attaching the screenshot and the device details below for reference. Hence closing this bug.

Screenshots: -
![image](https://user-images.githubusercontent.com/124761463/227435037-657da39d-8533-4dbf-97ab-5df01f9a7ba1.png)
![image](https://user-images.githubusercontent.com/124761463/227435071-741f7e57-e5de-41df-93f6-b994dfafa213.png)
![image](https://user-images.githubusercontent.com/124761463/227435125-e1eac1c3-3f06-4493-87b3-695c7c035f4a.png)

Tested in: -
Device: Redmi 7A
Android Version: 10
BLE version: 4.2
Inji app link: https://github.com/mosip/inji/actions/runs/4447486079
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Closed** 2023-03-24 05:53 UTC
Labels: bug, triage, Major
