### ISSUE TITLE
Android - Unable to bind downloaded VC

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#601] opened 2023-03-01 08:00 UTC
**Describe the bug**
We are unable to bind downloaded VC intermittently 

**To Reproduce**
Prerequisite: Download VC and store in the app

Steps : 
1. Unlock the app
2. click on Add ID
3. Enter VID
4. click on Generate ID
5. Click on the link "Activation pending for online login " on the card.
6. Click on Activate button.
7. Enter OTP 

**Expected behavior**
We should be able to bind VC's successfully 

**Actual behavior**
We are not able to bind VC intermittently 

**Screenshots**
https://user-images.githubusercontent.com/102220709/222078113-23215649-8cce-4e9e-9fd4-03cb77ee4c4a.mp4

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/222078290-67c341e5-a58f-4f3d-9776-9dad48309dff.png)

**Smartphone :**
  - Phone make/model: Redmi Note 10 lite 
  - OS: Android 10 
  - BLE version : 5.0
- MOSIP Version : 1.2.0.1
- MOSIP server : qa-1201-b2.net
- APP link : https://github.com/mosip/inji/actions/runs/4293687772

**Comment by Sujithbn** [comment] 2023-04-03 10:17
@santhoshsunder : As discussed on triage call, will verify this bug on latest build and keep this bug under observation since we are unable to find the root cause of the issue.

**Comment by Raginikrishnamurthy** [comment] 2023-11-21 14:07
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/e7e5281a-851a-41d2-afbd-aa40eee59209)

**Closed by Raginikrishnamurthy** 2023-11-21 14:07 UTC
Labels: bug, triage, Critical, BLE
