### ISSUE TITLE
Cross platform: Intermittently sharing is not working

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#567] opened 2023-02-16 10:24 UTC
**Describe the bug**
Wallet stucks in Sharing screen with Cancel on the popup and Verifier stucks in "connected to device waiting for ID" with cancel on popup

**To Reproduce**
**Prerequisite:** Download VC on wallet.

1. Open scanner in wallet
2. Open qr code in verifier
3. Scan the qr code and select VC to share
4. Click on "Accept Request and choose ID " on wallet

**Current behavior**
Wallet stucks in Sharing screen with Cancel on the popup and Verifier stucks in "connected to device waiting for ID" with cancel on popup : sharing fails. (Out of 5 attempts sharing worked twice)

**Expected behavior**
Sharing should work consistently

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/219331223-aa375ffc-d11e-40b7-9a61-12e2db1f81c7.png)

**Smartphone (please complete the following information):**

**Wallet:**
Device: iPhone 11
OS: 15.6.1
Inji app version: 0.4.1 (18) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE: 5.0

**Verifier:**
Device: Galaxy A03 core
OS: Android 11
Inji app version: [https://mosip-team.slack.com/files/U04KHL40S3X/F04QEC4SCQY/io.mosip.residentapp-0.2.1-858-5fa5c9b-develop-dirty-mosip_20230215_1516_universal.apk](https://mosip-team.slack.com/files/U04KHL40S3X/F04QEC4SCQY/io.mosip.residentapp-0.2.1-858-5fa5c9b-develop-dirty-mosip_20230215_1516_universal.apk?origin_team=TQFABD422&origin_channel=D03581C1Q2K)
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE: 4.2
![image](https://user-images.githubusercontent.com/79500509/219336944-8da0008e-c13e-4b55-9b1d-584257854058.png)

[crossptfm_logs.txt](https://github.com/mosip/inji/files/10754864/crossptfm_logs.txt)

**Comment by krishnakumar4a4** [comment] 2023-02-20 05:36
QA team observed this issue on Feb 15th build. Dev QA analysis have following outcomes
- Transfer report request seems to not go from IOS device to Android Verifier (3 out of 5 times)
- Apparently, happening only when Verifier device is `Galaxy A03 core`

**Comment by Anushree09-N** [comment] 2023-02-20 14:20
Able to replicate the issue in below set of combinations :
1. -----------------------------------------------------------
**Verifier:** 
Device: Redmi k20 pro 
OS : Android 11 
BLE 5.0

**Wallet**
 Device: iphone 11 
 OS: iPhone 15 
 Inji app version: 0.4.1 (18) -> Testflight
 BLE 5.0

Observed: 
1. Failed to share VC in the 3rd attempt.
2. Failed to share VC in 4th attempt .after restarting the verifier app

**Version** 
![image](https://user-images.githubusercontent.com/79500509/220129296-71576ff1-ed99-4cfe-a3a5-fe2268fffc08.png)

![image](https://user-images.githubusercontent.com/79500509/220130160-8b9028de-d00e-42c2-98a3-c496677069ea.png)

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

2. -------------------------------------------------------------------------

**Verifier:** 
Device: Redmi 6A 
OS : Android 9
BLE 4.2

**Wallet**
 Device: iphone 7 
 OS: iphone 15.6 
 Inji app version: 0.4.1 (18) -> Testflight
 BLE 4.2

Observed: 
1. VC share failed in 2nd attempt . Wallet displayed "ID  has been sent". Verifier displayed "Connected to the device waiting 
for ID".
2. VC share failed in 1st attempt after restarting verifier app

**Version** 
![image](https://user-images.githubusercontent.com/79500509/220129296-71576ff1-ed99-4cfe-a3a5-fe2268fffc08.png)

![image](https://user-images.githubusercontent.com/79500509/220130160-8b9028de-d00e-42c2-98a3-c496677069ea.png)

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

**Comment by Alka1703** [comment] 2023-02-24 13:47
This issue was due to transfer report getting stuck during the VC transfer. After adding the fix for iOS duplicate events, we observed that the issue is no longer reproducible on our devices(it was reproducible earlier).

PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/26
PR for mosip/inji:https://github.com/mosip/inji/pull/584

The PRs have been merged in 24-02-2023 Release and the latest commit id on mosip/inji/develop is `cb47493`

**Comment by damodarguru** [comment] 2023-03-28 07:20
Verified this issue in qa-1201-b2 environment, issue is not occurring. Verified with above mentioned devices, we share VC card multiple times every time it shares without any failure. I am attaching the screenshots and the device details below for reference. Hence closing the bug.

Screenshots: -
![image](https://user-images.githubusercontent.com/124761463/228158081-c1eb9207-d502-4999-b6fe-e42637d46d77.png)
![image](https://user-images.githubusercontent.com/124761463/228158169-6e65b0b2-9c62-46d1-8b9b-5dc170aa837f.png)
Tested in: -

![image](https://user-images.githubusercontent.com/124761463/228158386-dbb7d343-1b01-4198-9717-4f327e4bfe3a.png)
![image](https://user-images.githubusercontent.com/124761463/228158440-8a4de5d8-64fb-403f-8345-e09200f6c454.png)
Tested in: -

![image](https://user-images.githubusercontent.com/124761463/228158623-2309b6d7-400d-46fa-8bd3-0d25c5efbfd6.png)
![image](https://user-images.githubusercontent.com/124761463/228158679-cf2c1aeb-2e25-4ed9-924b-99c24dff6283.png)
Tested in: -
Wallet:
Device: iPhone 11
OS: 15.6.1
Inji app version: 0.4.1 (18) -> Testflight
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE: 5.0

Verifier:
Device: Galaxy A03 core
OS: Android 11
Inji app version: [https://mosip-team.slack.com/files/U04KHL40S3X/F04QEC4SCQY/io.mosip.residentapp-0.2.1-858-5fa5c9b-develop-dirty-mosip_20230215_1516_universal.apk](https://mosip-team.slack.com/files/U04KHL40S3X/F04QEC4SCQY/io.mosip.residentapp-0.2.1-858-5fa5c9b-develop-dirty-mosip_20230215_1516_universal.apk?origin_team=TQFABD422&origin_channel=D03581C1Q2K)
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE: 4.2

**Closed** 2023-03-28 08:48 UTC
Labels: bug, triage, Critical, BLE, BLE-Sharing
