### ISSUE TITLE
Remove activation button for all the Cards in the Sharing Card screen

### ISSUE THREAD

**Issue by PuBHARGAVI** [mosip/inji#647] opened 2023-03-15 13:39 UTC
**Describe the issue:**
Currently we are showing the activation status/button for all the cards in the Sharing Card screen. This status doesn't make any sense while sharing the VC. As per the discussion with @nayakrounak and @rakhimosip it is decided to remove the activation status

**Current Behaviour:**
![image](https://user-images.githubusercontent.com/46226958/225325150-398e5210-b988-4102-80ce-a719084786fd.png)

**Expected Behaviour:**
Activation status should be removed for the cards in Sharing Card screen

**Comment by PuBHARGAVI** [comment] 2023-03-16 06:19
Removed the activation status for the cards in the Sharing Card screen.
<img width="404" alt="Screenshot 2023-03-16 at 11 49 21 AM" src="https://user-images.githubusercontent.com/46226958/225531714-50133c8f-9328-4729-87b2-8d92424d4d23.png">

**Comment by krishnakumar4a4** [comment] 2023-03-24 14:27
> Removed the activation status for the cards in the Sharing Card screen. <img alt="Screenshot 2023-03-16 at 11 49 21 AM" width="404" src="https://user-images.githubusercontent.com/46226958/225531714-50133c8f-9328-4729-87b2-8d92424d4d23.png">

Quoted reply from @PuBHARGAVI for fix details, the fix is done as part of 24-03-2023 release

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by santhoshsunder** [comment] 2023-03-28 05:46
Verified this issue in the new build, and the issue is not observed anymore, we are unable to see the action button, hence closing this bug 

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/228139947-da3c923c-f771-4edb-a638-6f6baebbd943.png)


Tested on :
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Closed by santhoshsunder** 2023-03-28 05:46 UTC
Labels: enhancement, BLE
