### ISSUE TITLE
Android - faced "Not in GZIP format" error on the logs when app is crashed (GCM issue)

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#542] opened 2023-02-07 12:16 UTC
**Describe the bug**
faced "Not in GZIP format" error on the logs when app is crashed while sharing VC 

**To Reproduce**

Prerequisite:
device A - IOS (wallet) --> VC is downloaded and stored
device B - Android (verifier)

Steps:
1. Scan the qr code from device A
2. Select VC to share
3. Click on "Accept request and choose ID" button
4. Check the logs

**Expected behavior**
app should not crash and no error message should be logged on the logs

**Observed**
the app is crashing on verifier device and we are seeing this "Not in GZIP format" error on the logs, attaching the logs bellow

**Smartphone :**
- Device B : redmi k20 pro
- OS: Android 11
- Inji app version : https://github.com/mosip/inji/actions/runs/4062244892
- MOSIP Version: 1.2.0.1
- MOSIP server: qa-1201-b2.mosip.net
- BLE version: 5.0

**Logs**
```FATAL EXCEPTION: TransferHandlerThread
                                                                                                    Process: io.mosip.residentapp, PID: 25165
                                                                                                    java.lang.RuntimeException: Error while decompression!
                                                                                                    	at io.mosip.tuvali.transfer.Util$Companion.decompress(Util.kt:67)
                                                                                                    	at io.mosip.tuvali.verifier.Verifier.onResponseReceived(Verifier.kt:229)
                                                                                                    	at io.mosip.tuvali.verifier.transfer.TransferHandler.handleMessage(TransferHandler.kt:88)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:236)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.util.zip.ZipException: Not in GZIP format
                                                                                                    	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:174)
                                                                                                    	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:83)
                                                                                                    	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:100)
                                                                                                    	at io.mosip.tuvali.transfer.Util$Companion.decompress(Util.kt:65)
                                                                                                    	at io.mosip.tuvali.verifier.Verifier.onResponseReceived(Verifier.kt:229) 
                                                                                                    	at io.mosip.tuvali.verifier.transfer.TransferHandler.handleMessage(TransferHandler.kt:88) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:236) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)```

**Comment by krishnakumar4a4** [comment] 2023-02-08 04:35
@santhoshsunder This bug is exactly same as #525 . The build and stack trace is same except the verifier device being different. So can we add these details to #525 itself.

**Comment by gsasikumar** [comment] 2023-02-14 05:26
Please split the fix into two activities. First one to handle the exception & second one to find the root cause and fix.

**Comment by krishnakumar4a4** [comment] 2023-02-14 10:50
@santhoshsunder Please note that earlier issue description says this was happening between IOS Wallet and Android Verifier. My earlier comment was inline with that description. Now the description seems to have been edited to device A and device B with no details about device A & B.

Could you provide 
- Exact device combination and details(both sending and receiving device) on which this issue was reproduced 
- and also the profile page screenshots for both devices to confirm the build details

**Comment by Raginikrishnamurthy** [comment] 2023-02-15 07:14
@krishnakumar4a4 Please find the device detail in the bug description above, anyways adding here again:

Device: redmi k20 pro
OS: Android 11
Inji app version : https://github.com/mosip/inji/actions/runs/4062244892
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net
BLE version: 5.0

**Comment by santhoshsunder** [comment] 2023-02-15 07:17
Linking this "https://github.com/mosip/inji/issues/515" related bug for reference

**Comment by santhoshsunder** [comment] 2023-02-16 06:17
Retaining back the original description as it is not duplicate issue for #525. The issue was surfaced when the sharing was initiated by ios and unable to decrypt on Android in GZIP format. This is completely different issue as compared to #525

**Comment by Alka1703** [comment] 2023-02-20 12:59
On IOS wallet, we have observed the secrets are getting initialised multiple times. This is because of initialisation is being done on receiving an advertisement. Hence during a normal VC transfer, if there is a possibility of another device advertising can cause re-initialisation of the secrets also which could eventually result in a decryption error (GCM error).

The following PRs would possibly address this issue: 
PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/24
PR for mosip/inji: https://github.com/mosip/inji/pull/573

The PRs have been merged in 20-02-2023 Release and the latest commit id on mosip/inji/develop is 6df8076

**Comment by Anushree09-N** [comment] 2023-02-27 11:21
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

App version: 
![image](https://user-images.githubusercontent.com/79500509/220966559-047985ab-0f99-4ffb-8b53-517edfe162c9.png)

Verified in below device combinations in debug build:
![image](https://user-images.githubusercontent.com/79500509/220966100-da8e4c16-b194-4e89-b431-3eb11431772d.png)

Issue not observed in the logs, Will re-verify the ticket in release build.

**Comment by Sujithbn** [comment] 2023-03-15 10:13
@Anushree09-N : Please verify this and close it today

**Comment by Raginikrishnamurthy** [comment] 2023-03-16 12:40
Crash issue is not observed on the above-mentioned device combination, hence closing the bug.

**Closed by Raginikrishnamurthy** 2023-03-16 12:40 UTC
Labels: bug, triage, Critical, BLE, P2, BLE-Sharing
