### ISSUE TITLE
Mobile id - While sharing VC the reason optional text box has issues [text box within a text box].

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#99] opened 2022-09-07 05:56 UTC
**Describe the bug**
Mobile id - While sharing VC the reason optional text box has issues [text box within a text box].

**To Reproduce**
1. Open the app in the two mobiles
2. Turn on bluetooth in both the mobiles
3. Now have one mobile in request state and from another mobile scan QR code  
4. From the phone you have scanned the QR code, will be now in sharing VC screen
5. Click on the reason for sharing textbox

**Current behavior**
When we enter the first letter the textbox getting replaced by a new textbox and the single letter that we are typing is disapearing in seconds as shown in the attached video

**Expected behavior**
The textbox should get the inputs normally and any letters should not dissaper 

**Screenshots**

https://user-images.githubusercontent.com/79500509/188799260-c31db25a-c2df-433a-967e-0dbe0e58a532.mp4

**Smartphone (please complete the following information):**
- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**
qa4.mosip.net

**Comment by Anil-kumar-Majji** [comment] 2022-09-28 11:48
The bug was fixed and PR has been raised.

**Comment by Anil-kumar-Majji** [comment] 2022-09-28 11:48
The bug was fixed and PR has been raised.

**Comment by Anil-kumar-Majji** [comment] 2022-09-28 11:48
The bug was fixed and PR has been raised.

**Comment by Sujithbn** [comment] 2022-11-07 11:23
Please verify this in the latest IOS 16 build and confirm us.

**Comment by santhoshsunder** [comment] 2022-11-16 11:50
Tested this issue in QA-121 env, the issue is not observed any more, hense closing this bug

**Closed by santhoshsunder** 2022-11-16 11:50 UTC
Labels: bug, Sprint_13, triaged, Retest
