### ISSUE TITLE
The Get UIN/VID from AID is retrieving VID on UIN dropdown's textbox 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#673] opened 2023-03-28 06:30 UTC
**Describe the bug**
The Get UIN/VID from AID is retrieving VID on UIN dropdown's textbox 

**To Reproduce**
1. Unlock the app
2. click on ADD ID button on the home page
3. click on "Don't have your UIN/VID? Get it here " link.
4. Enter AID
5. click on Get UIN/VID button
6. enter the OTP 

**Expected behavior**
The retrieved VID should be entered in the VID's dropdown

**Actual behavior**
The retrieved AID is entered under the UIN's dropdown, if we select the VID drop-down next, the page gets refreshed, and the retrieved VID is disappearing 

**Screenshots**
https://user-images.githubusercontent.com/102220709/228147721-ecd134ea-f8d5-4920-abd4-988f68312021.mp4

**Add the screenshot of the profile page with commit id**
![image](https://user-images.githubusercontent.com/102220709/228147876-8a680551-4b89-43d2-89d7-bb3d13b93478.png)

Tested on :
This issue is occurring in both ios and android 
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Comment by hegdenitin** [comment] 2024-07-26 12:26
verified the issue in the current build the issue is not occurring because currently, we have only an e-signet flow to download the VC Hence closing the bug

**Closed by hegdenitin** 2024-07-26 12:26 UTC
Labels: bug, triage, Major, BLE
