### ISSUE TITLE
Cross platform: Disconnect pop up displayed on verifier device in subsequent sharing.

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#577] opened 2023-02-21 15:19 UTC
**Describe the bug**
Disconnect pop up displayed on verifier device in subsequent sharing.

**To Reproduce**
1. Scan the qr code (verifier) from wallet.
2. Select VC to share 
3. click on "Accept request and choose ID" button. -->success pop up displayed on both device
4. Repeat step 1,2 & 3 several times subsequently

**Current behavior**
After Several attempts of sharing clicked on scanner in wallet and parallely clicked on qr code icon in verifier phone, the disconnect error occurred on verifier phone in 12th and 16th attempt of sharing. 

**Expected behavior**
Should not have disconnect error pop up 

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/220381918-24d7c13b-6a1b-43f1-a839-134768cf58ee.png)

**Smartphone (please complete the following information):**

Wallet: iphone 7 | iphone 15.6 BLE 4.2

Verifier: Redmi 6A | Android 9 BLE 4.2

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

APK: 
![image](https://user-images.githubusercontent.com/79500509/220384040-b9b59b44-5537-4e6e-aaed-81d918d8d90a.png)

logs: 
[redmi6a21feb.txt](https://github.com/mosip/inji/files/10794870/redmi6a21feb.txt)

![image](https://user-images.githubusercontent.com/79500509/220384844-857723d5-8d51-40e7-a4cf-6a459fc71985.png)

iOS app: 0.4.1 (19) ---testflight.

**Comment by Anushree09-N** [comment] 2023-02-22 08:05
Disconnect error occurred for below set of combinations: Debug build

**Verifier** : Redmi k20 pro | Android 11 BLE 5.0
**Wallet** :  iphone 8 | iphone 16 BLE 5.0

**Logs**: 
[Redmik20pro22feb.txt](https://github.com/mosip/inji/files/10801344/Redmik20pro22feb.txt)

![image](https://user-images.githubusercontent.com/79500509/220558999-5928f12f-574e-447c-ab5b-839c6cb48260.png)

![image](https://user-images.githubusercontent.com/79500509/220559217-86f3ceaf-c4b2-4e39-a99b-792cf3c5dc2a.png)

**Observed** : Disconnect issue occured in 2nd and 6th attempt.

**Comment by ravikp** [comment] 2023-02-22 09:10
@Anushree09-N - the disconnect issue occurred twice(2nd, and 6th) in how many rounds of testing on the same device combination?

**Comment by Alka1703** [comment] 2023-02-23 07:00
@Anushree09-N  The logs attached are not proper. It does not contain any logs from the tuvali layer. 
I installed the same apk and I can see the tuvali layer logs in android studio console.

**Comment by Anushree09-N** [comment] 2023-02-23 10:57
@Alka1703 As discussed over call Attaching the logs without applying any filter. Hope this will help for further analysis.

Device used to replicate the issue :

Verifier : Redmi k20 pro | Android 11 BLE 5.0
Wallet : iphone 8 | iphone 16 BLE 5.0

MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.mosip.net

App Version: 
![image](https://user-images.githubusercontent.com/79500509/220887445-75297372-5217-4a31-a2aa-15c893b04d51.png)

Logs: 

[Redmik20pro22feb.txt.txt](https://github.com/mosip/inji/files/10812731/Redmik20pro22feb.txt.txt)

**Comment by Anuranjan14** [comment] 2023-03-06 07:53
Observed the same issue while doing face authentication in new build with below mentioned devices and attaching the screenshot for the reference.

Screenshot : 
![image](https://user-images.githubusercontent.com/120705365/223049933-952e55b9-f52d-4644-b7f1-653b08453e0d.png)

Device used to replicate the issue :

Verifier : Redmi 7A | Android 10 BLE 4.2
Wallet : iphone 7 | IOS 15.6 BLE 4.2

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4293687772
IPA Testflight version : 0.4.1 (21)

**Comment by Sujithbn** [comment] 2023-03-15 10:46
This issue will not be prioritized for the 0.9 release. will be taken up post release.

**Comment by santhoshsunder** [comment] 2023-03-20 06:57
verified this issue in my personal phone with the current build, the issue is still occurring, with my android pixel 6, any ios devices are connecting or able to send VC successfully, not even a single attempt, hence reopening this bug, iam attaching screenshots below for reference, and adding my personal device details

screenshot : 
![image](https://user-images.githubusercontent.com/102220709/226268156-2ac752ab-998d-4c13-86e6-281473f19eed.png)
![image](https://user-images.githubusercontent.com/102220709/226268185-c26d2b45-caf9-4b3b-9df6-08ff6c2f1a02.png)

tested on : 

verifier : pixel 6
android : 13
ble : 5.2

wallet : iphone 7
IOS  : 15.6
ble : 4.2

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079
testflight ipa : 0.4.1 (29)

**Comment by vharsh** [comment] 2023-03-20 09:47
For iPhone7 --> Pixel6 the transfer is failing because of **TooManyChunksFailureException** which is happening due to CRC mismatch.


```
# <crcReceivedNotEqualToCrcCalculated came 730 times for VID 6215701682938419(BIG VC ~700KB) !>
...
...
03-20 14:47:46.921 30743  3801 E CheckValue : v0.3.8: crcReceivedNotEqualToCrcCalculated crcReceived: 47228, crcCalculated: 38127
03-20 14:47:46.982 30743  3801 E CheckValue : v0.3.8: crcReceivedNotEqualToCrcCalculated crcReceived: 59170, crcCalculated: 4705
03-20 14:47:47.019 30743  3801 E Openid4vpBleModule : vunknown: Exception: Exception in Verifier Transfer Handler
03-20 14:47:47.019 30743  3801 E VerifierExceptionHandler : vunknown: Verifier Exception: io.mosip.tuvali.verifier.exception.TooManyFailureChunksException: Failing VC transfer as failure chunks are more than 70% of total chunks
03-20 14:47:47.022 30743  3801 D Openid4vpBleModule : vunknown: synchronized destroyConnection called for verifier at 67945761691134
03-20 14:47:47.022 30743  3801 D Openid4vpBleModule : vunknown: stopVerifier: setting to null
03-20 14:47:47.022 30743  3802 D StateHandler : v0.3.8: stopping advertisement
03-20 14:47:47.022 30743  3801 D TransferHandler : v0.3.8: dispatchMessage Failing VC transfer as failure chunks are more than 70% of total chunks
03-20 14:47:47.023 30743  3802 D StateHandler : v0.3.8: sendData: uuid: 00002038-0000-1000-8000-00805f9b34fb, dataSize: 1, data: 01
03-20 14:47:47.026 30743  3802 I Controller : v0.3.8: Is notification triggered for char 00002038-0000-1000-8000-00805f9b34fb: true
03-20 14:47:47.026 30743  3802 D StateHandler : v0.3.8: sendData: uuid: 00002038-0000-1000-8000-00805f9b34fb, isNotified: true
03-20 14:47:47.028 30743  3802 D StateHandler : v0.3.8: disconnect and close gatt server
03-20 14:47:47.028 30743 30805 I ReactNativeJS: BLE Exception: Failing VC transfer as failure chunks are more than 70% of total chunks
03-20 14:47:47.028 30743  3802 D GattServer : v0.3.8: Disconnecting from central with device address: 43:EE:0F:F3:F4:35
03-20 14:47:47.028 30743  3802 D BluetoothGattServer: cancelConnection() - device: 43:EE:0F:F3:F4:35
```

iPhone7 logs
```
Mar 20 14:47:24 iPhone bluetoothd[87] <Notice>: Received XPC message "CBMsgIdCharacteristicWriteValue" from session "io.mosip.inji.mobileid-central-344-143"
Mar 20 14:47:24 iPhone bluetoothd[87] <Notice>: Writing value without response to characteristic handle 0x0090 on device "<private>"
Mar 20 14:47:24 iPhone bluetoothd[87] <Notice>: Using Write Without Response
Mar 20 14:47:24 iPhone bluetoothd[87] <Error>: Failed to write request for bearer 0x04506F00  STATUS 4001 (status=65535)
Mar 20 14:47:24 iPhone bluetoothd[87] <Error>: Command failed to execute with status 4001
Mar 20 14:47:24 iPhone bluetoothd[87] <Error>: Command failed to execute with status 4001
Mar 20 14:47:24 iPhone bluetoothd[87] <Error>: Unhandled stack status: 4001

Mar 20 14:47:24 iPhone bluetoothd[87] <Notice>: Received XPC message "CBMsgIdCharacteristicWriteValue" from session "io.mosip.inji.mobileid-central-344-143"
Mar 20 14:47:24 iPhone bluetoothd[87] <Notice>: Writing value without response to characteristic handle 0x0090 on device "<private>"
Mar 20 14:47:24 iPhone bluetoothd[87] <Notice>: Using Write Without Response




Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Received XPC message "CBMsgIdCharacteristicWriteValue" from session "io.mosip.inji.mobileid-central-344-143"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Writing value without response to characteristic handle 0x0090 on device "<private>"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Using Write Without Response
Mar 20 14:47:25 iPhone backboardd(CoreBrightness)[65] <Notice>: Lcurrent=210.5043 Lr=2.0881 DR=100.8101 factor=0.0722
Mar 20 14:47:25 iPhone backboardd(CoreBrightness)[65] <Notice>: Lcurrent=210.5043 Lr=2.0880 DR=100.8142 factor=0.0722
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Received XPC message "CBMsgIdCharacteristicWriteValue" from session "io.mosip.inji.mobileid-central-344-143"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Writing value without response to characteristic handle 0x0090 on device "<private>"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Using Write Without Response
Mar 20 14:47:25 iPhone bluetoothd[87] <Error>: Failed to write request for bearer 0x04506F00  STATUS 4001 (status=65535)
Mar 20 14:47:25 iPhone bluetoothd[87] <Error>: Command failed to execute with status 4001
Mar 20 14:47:25 iPhone bluetoothd[87] <Error>: Command failed to execute with status 4001
Mar 20 14:47:25 iPhone bluetoothd[87] <Error>: Unhandled stack status: 4001
Mar 20 14:47:25 iPhone backboardd(CoreBrightness)[65] <Notice>: Lcurrent=210.5043 Lr=2.0880 DR=100.8184 factor=0.0722
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Received XPC message "CBMsgIdCharacteristicWriteValue" from session "io.mosip.inji.mobileid-central-344-143"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Writing value without response to characteristic handle 0x0090 on device "<private>"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Using Write Without Response
Mar 20 14:47:25 iPhone backboardd(CoreBrightness)[65] <Notice>: Lcurrent=210.5043 Lr=2.0879 DR=100.8225 factor=0.0722
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Received XPC message "CBMsgIdCharacteristicWriteValue" from session "io.mosip.inji.mobileid-central-344-143"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Writing value without response to characteristic handle 0x0090 on device "<private>"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Using Write Without Response
Mar 20 14:47:25 iPhone backboardd(CoreBrightness)[65] <Notice>: Lcurrent=210.5043 Lr=2.0878 DR=100.8266 factor=0.0722
Mar 20 14:47:25 iPhone backboardd(CoreBrightness)[65] <Notice>: Lcurrent=210.5043 Lr=2.0877 DR=100.8308 factor=0.0722
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Received XPC message "CBMsgIdCharacteristicWriteValue" from session "io.mosip.inji.mobileid-central-344-143"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Writing value without response to characteristic handle 0x0090 on device "<private>"
Mar 20 14:47:25 iPhone bluetoothd[87] <Notice>: Using Write Without Response
Mar 20 14:47:25 iPhone bluetoothd[87] <Error>: Failed to write request for bearer 0x04506F00  STATUS 4001 (status=65535)
```

Full iOS Logs attached.

[iphone7-pixel6-3.txt](https://github.com/mosip/inji/files/11016281/iphone7-pixel6-3.txt)

**Comment by vharsh** [comment] 2023-03-20 10:14
I've checked it against iOS 15.7.3 on another iPhone7 and I'm still seeing similar issue. Since this seems to be a separate set of devices from originally reported device combination I'm not collecting the logs for this one in priority and I'd do it tomorrow.

**Comment by vharsh** [comment] 2023-03-20 11:41
With iPhone7 --> Redmi6A, I'm not able to reproduce it.

**Comment by vharsh** [comment] 2023-03-20 11:56
With iPhone8 --> K20 Pro, I'm not able to reproduce this with 23 VC transfers.

**Comment by vharsh** [comment] 2023-03-20 13:33
With iPhone8 --> K20 Pro, I'm not able to reproduce this with 22 VC transfers with the 700KB VC too.

**Comment by vharsh** [comment] 2023-03-21 04:50
@Anushree09-N Please share the device combination where this bug was observed yesterday evening.

**Comment by damodarguru** [comment] 2023-03-21 06:04
Able to replicate this issue in Redmi K20 Pro and Vivo Y73 phone with the current build, Disconnect pop is displayed when sharing of VC was initiated.  I am attaching video below for reference, and adding device details.

Video:
https://user-images.githubusercontent.com/124761463/226528668-a9121913-6f28-4c51-a6a0-40cd9a690b54.mp4
![image](https://user-images.githubusercontent.com/124761463/226529695-0c0d0203-b3fc-493e-8dc6-e0aaed21071f.png)

Tested on:
Verifier: Redmi K20 Pro
Android: 11
Ble: 5.0

Wallet: Vivo Y73
Android: 12
Ble: 5.0

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4447486079

**Comment by vharsh** [comment] 2023-03-21 06:18
> Able to replicate this issue in Redmi K20 Pro

@damodarguru After how many successful transfers was this issue observed?

**Comment by Anushree09-N** [comment] 2023-03-21 06:33
@vharsh As you saw the issue occured in first attempt.

**Comment by Alka1703** [comment] 2023-03-21 08:11
> Able to replicate this issue in Redmi K20 Pro and Vivo Y73 phone with the current build, Disconnect pop is displayed when sharing of VC was initiated. I am attaching video below for reference, and adding device details.
> 
> Video: https://user-images.githubusercontent.com/124761463/226528668-a9121913-6f28-4c51-a6a0-40cd9a690b54.mp4 ![image](https://user-images.githubusercontent.com/124761463/226529695-0c0d0203-b3fc-493e-8dc6-e0aaed21071f.png)
> 
> Tested on: Verifier: Redmi K20 Pro Android: 11 Ble: 5.0
> 
> Wallet: Vivo Y73 Android: 12 Ble: 5.0
> 
> MOSIP Version : 1.2.0.1 MOSIP server : qa-1201-b2.net APP link : https://github.com/mosip/inji/actions/runs/4447486079

@damodarguru we already have an issue created for this. Please refer to this one: https://github.com/mosip/inji/issues/523
And this issue deals with cross platform disconnect events. Please be mindful on the device combination the next time.

**Comment by santhoshsunder** [comment] 2023-03-29 11:00
Tested the issue in the new build, the issue is still occurring, we are unable to receive VCs from IOS to android 13 devices,facing this disconnect issue, hence reopening the bug

Screenshot :
![image](https://user-images.githubusercontent.com/102220709/228513258-828ddb44-ad5d-43db-889a-fee4aa3b128e.png)

Tested on:

- Wallet Device:
Phone make/model: Apple iPhone 7
OS: iOS 15
BLE version : 4.2

- Verifier Device:
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Comment by santhoshsunder** [comment] 2023-11-28 12:38
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/4d1299ce-fcac-4f15-b484-2712a3dcb116)

**Closed by santhoshsunder** 2023-11-28 12:38 UTC
Labels: bug, triage, Major, BLE-Sharing, MEC
