### ISSUE TITLE
Android - the face auth is failing even in correct attempt 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#434] opened 2023-01-17 11:49 UTC
**Describe the bug**
the face auth is failing even in correct matching face attempt 

**To Reproduce**
prerequisite : Device A --> Requesting
Device B --> Sharing

**Steps :**
1. Open qrcode in Device A
2. Open scanner in Device B
3. Scan the qrcode from Device B
4. In the sharing ID screen in device B, select the UIN card you want share
5. And select any attempt of face auth sharing method
6. When the camera is opened, capture the face with matching face 

**Expected behavior**
The app should identify the face and should aprove to share VC

**Observed :**
The app is showing the error message for the matching face too

**Screenshots**
when consent is given 
https://user-images.githubusercontent.com/102220709/212890478-5513def9-0226-4600-b6e7-3b90283a2411.mp4

while accept request and verify
https://user-images.githubusercontent.com/102220709/212891005-1fee18b4-624e-48a5-9fb4-623e173a68e9.mp4

**Smartphone :**
- Device: PIXEL 6
- OS: Android 13
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Comment by rakhimosip** [comment] 2023-02-03 10:21
NOTE
-
- The face-auth model is downloaded as a background process by the app. 
- The root cause might be the face-auth model not being downloaded fully. Incomplete model download 

Workaround -> clear cache -> this will initiate a fresh download of the model

Alternate solutions proposed 
-
- Have a fallback model packaged into the app that can be used in case of incomplete downloads
- Incorporate a validation in place for the model at both publisher and subscriber's end.

Open questions
- Need a proper design for downloading the model. Currently, it is being stored on a Google drive

Need inputs to address this issue from @gsasikumar 
cc @MonobikashDas @ravikp

**Comment by santhoshsunder** [comment] 2023-03-06 10:48
Verified this issue in the new build, able to replicate this issue intermittently, faced it here and there while id login and sharing with  face auth, the app is not recognizing the resident face, iam attaching the issue video and the details below, hence reopening this issue 

Video : 
https://user-images.githubusercontent.com/102220709/223089295-71700de3-b31e-411e-8149-76d41f1dd47c.mp4

Mobile details :
Phone make: Pixel 6
OS: Android 13
BLE version : 5.2
MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4293687772

**Comment by Raginikrishnamurthy** [comment] 2023-03-15 12:46
@Sujithbn The issue is still occuring intermittently for which we have another bug to track.
https://github.com/mosip/inji/issues/524
changing the severity to Major as we need inputs from Sasi for Rakhi's questions.

**Comment by Raginikrishnamurthy** [comment] 2023-11-21 14:43
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/30d12a71-d29f-4548-9312-e06a4b81025c)

**Closed by Raginikrishnamurthy** 2023-11-21 14:43 UTC
Labels: bug, Major, triaged, Review
