### ISSUE TITLE
Unable to download VC

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#178] opened 2022-10-20 12:44 UTC
**Describe the bug**
Unable to download VC, error message showing "uin not available in database"

**To Reproduce**
1. Open app and head to home page
2. Click on add ID 
3. Enter a valid UIN and click on generate VID

**Expected behavior**
should able to download VC with out any errors

**Observed behavior**
Unable to download VC, error message showing "uin not available in database"

**Screenshots**
![image](https://user-images.githubusercontent.com/102220709/196951586-ea32b2dc-18c6-4041-9183-d23745a1bb50.png)

**Smartphone (please complete the following information):**
Device: android
MOSIP Version: 121
MOSIP server: qa-121.mosip.net
APK link : https://github.com/mosip/inji/actions/runs/3287270987

**Comment by Sujithbn** [comment] 2022-10-31 04:48
@Anushree09-N : Please let us know if this issue is still persists, if not update and close the issue.

**Comment by Anushree09-N** [comment] 2022-11-04 08:13
@Sujithbn The issue is resolved now but we would like to know what was the fix given?

**Comment by Sujithbn** [comment] 2022-11-07 13:27
APK was pointing to QA4 environment, Mono has changed this to QA-121 environment to fix this issue.

**Comment by Anushree09-N** [comment] 2022-11-14 03:46
Verified in 1.2.1 ,qa-121.mosip.net. Working as expected able to download VC.
![image](https://user-images.githubusercontent.com/79500509/201571036-dd6afaa8-0c33-4c64-b44d-b303c75d9a5e.png)

**Closed by Anushree09-N** 2022-11-14 03:46 UTC
Labels: bug, blocker, triaged, beta_must_fix
