### ISSUE TITLE
iOS doesn’t turn on bluetooth if disabled when Scanner is opened

### ISSUE THREAD

**Issue by PoojaBabusing** [mosip/inji#580] opened 2023-02-23 09:48 UTC
**Describe the bug**
On entering the scan screen on ios side the device asks for bluetooth permission "Bluetooth is used to allow sharing VCs with another device". The expected behaviour post this is to ask the user to turn on the bluetooth. 

**Steps to reproduce the behaviour:**
- Install the app. Allow the local network request.
- Add id. keep the bluetooth off
- go to the scan screen. You will receive "Bluetooth is used to allow sharing VCs with another device" allow it.
- now if you check, the bluetooth will not be enabled.

**Expected behaviour**
Post giving the permission to use bluetooth, the app should request to turn on bluetooth.

**Screenshots**
![IMG_2964](https://user-images.githubusercontent.com/115976560/220870764-bc989561-2541-40df-9713-172e7ccec62e.PNG)

**Smartphone (please complete the following information):**

Device: iPhone 11
OS: iOS 16.2j
Inji app version: [0.4.1]
MOSIP Version: [e.g. 1.0.0]
MOSIP server: https://api.collab.mosip.net/

**Comment by vharsh** [comment] 2023-03-17 12:21
The following change is available on branch=0.9 & on branch=develop as part of the 17th March, 2023 release.

PR for mosip/inji(branch=develop): https://github.com/mosip/inji/pull/655,
commit: https://github.com/mosip/inji/commit/aff1c4f7b96d27f1c8f54e62d3f03a7086473f35
PR for mosip/inji(branch=0.9): https://github.com/mosip/inji/pull/653
commit: https://github.com/mosip/inji/commit/4c2ca4b0ea400cb29cb59ee6a87106e2542023da

**Comment by santhoshsunder** [comment] 2023-03-23 11:22
Tested this issue in the new build, the issue is not observed anymore, when the Bluetooth is turned off, the camera is not opening, it is working as expected, hence closing the bug 

Screenshot : 
https://user-images.githubusercontent.com/102220709/227188780-5c57b169-8312-4c8d-81ac-3ebc91f6461c.mp4

Tested on :
Device: iPhone 11
OS: 15.4.1
Inji app version: 0.4.1 (29) in test flight
MOSIP Version: 1.2.1
MOSIP server: qa-121.mosip.net

**Closed by santhoshsunder** 2023-03-23 11:22 UTC
Labels: bug, triage, BLE, BLE-Sharing, MEC
