### ISSUE TITLE
Pixel 6(Android 13) is not able to receive VCs from iOS devices

### ISSUE THREAD

**Issue by vharsh** [mosip/inji#665] opened 2023-03-22 11:14 UTC
**Describe the bug**

VC transfers from iOS device always fail to reach the Android 13 verifier. Other generic Android phones are able to exchange VCs as per current analysis.  

**To Reproduce**

1. Use an Android 13 phone acting as a Verifier
2. Use any iPhone as a Wallet 
3. Initiate a VC transfer

The `Transfer Error` message is shown

**Expected behavior**
- VC Transfer should happen as expected

**Actual behavior**
- VC Transfer fails always and never happens successfully.
- Internally, the transfer fails when 70% of the chunks have been received incorrectly by verifier(expected behaviour)

**Screenshots**
![image](https://user-images.githubusercontent.com/9304050/226885608-b7ebbf8d-3c84-4dfd-8893-41f9087b197d.png)

**Add the screenshot of the profile page with commit id**

- happens for Google Pixel 6(Android 13)

**Smartphone (please complete the following information):**

- Wallet Device: 
  - Phone make/model: Apple iPhone 7
  - OS: iOS 15
  - BLE version : 4.2

- Verifier Device:
  - Phone make/model: Google Pixel 6
  - OS: Android 13
  - BLE version : 5.2

**Logs of wallet and verifier:**

```
# <crcReceivedNotEqualToCrcCalculated came 730 times for VID 6215701682938419(BIG VC ~700KB) !>
...
...
03-20 14:47:46.921 30743  3801 E CheckValue : v0.3.8: crcReceivedNotEqualToCrcCalculated crcReceived: 47228, crcCalculated: 38127
03-20 14:47:46.982 30743  3801 E CheckValue : v0.3.8: crcReceivedNotEqualToCrcCalculated crcReceived: 59170, crcCalculated: 4705
03-20 14:47:47.019 30743  3801 E Openid4vpBleModule : vunknown: Exception: Exception in Verifier Transfer Handler
03-20 14:47:47.019 30743  3801 E VerifierExceptionHandler : vunknown: Verifier Exception: io.mosip.tuvali.verifier.exception.TooManyFailureChunksException: Failing VC transfer as failure chunks are more than 70% of total chunks
03-20 14:47:47.022 30743  3801 D Openid4vpBleModule : vunknown: synchronized destroyConnection called for verifier at 67945761691134
03-20 14:47:47.022 30743  3801 D Openid4vpBleModule : vunknown: stopVerifier: setting to null
03-20 14:47:47.022 30743  3802 D StateHandler : v0.3.8: stopping advertisement
03-20 14:47:47.022 30743  3801 D TransferHandler : v0.3.8: dispatchMessage Failing VC transfer as failure chunks are more than 70% of total chunks
03-20 14:47:47.023 30743  3802 D StateHandler : v0.3.8: sendData: uuid: 00002038-0000-1000-8000-00805f9b34fb, dataSize: 1, data: 01
03-20 14:47:47.026 30743  3802 I Controller : v0.3.8: Is notification triggered for char 00002038-0000-1000-8000-00805f9b34fb: true
03-20 14:47:47.026 30743  3802 D StateHandler : v0.3.8: sendData: uuid: 00002038-0000-1000-8000-00805f9b34fb, isNotified: true
03-20 14:47:47.028 30743  3802 D StateHandler : v0.3.8: disconnect and close gatt server
03-20 14:47:47.028 30743 30805 I ReactNativeJS: BLE Exception: Failing VC transfer as failure chunks are more than 70% of total chunks
03-20 14:47:47.028 30743  3802 D GattServer : v0.3.8: Disconnecting from central with device address: 43:EE:0F:F3:F4:35
03-20 14:47:47.028 30743  3802 D BluetoothGattServer: cancelConnection() - device: 43:EE:0F:F3:F4:35
```

**Additional context**

- https://github.com/dariuszseweryn/RxAndroidBle/pull/808

**Comment by ravikp** [comment] 2023-03-23 06:44
This issue happens with Android 13 and Bluetooth 5.3 specification. The fix is to ensure that the max MTU is capped at 512.

**Comment by lsivanand** [comment] 2023-03-23 06:49
Do we need to cap the MTU ! As per dynamic MTU size negotiation, size will be fixed to the mutually agreed size between the devices

**Comment by vharsh** [comment] 2023-03-24 06:10
On further analysis with [Mi 11x](https://www.gsmarena.com/xiaomi_mi_11x-10775.php) against iPhone7(wallet) we observed it accepts 517 as the ATT_MTU and is able to receive 517-3=514bytes from iOS. So this issue seems to be specific to **Pixel 6**.

**Comment by krishnakumar4a4** [comment] 2023-03-24 14:34
We have made fix to not to expect data transfer to happen at 514 though it negotiated at 514, but instead ceil it at 512. This addresses the VC transfer failure we are seeing with iphone 7 and Pixel 6 (Android 13) quoted above. The fix is given in 24-03-2023 release:

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by santhoshsunder** [comment] 2023-03-28 10:25
Tested the issue in the new build, the issue is still occurring, we are unable to receive VCs from IOS to android 13 devices, hence reopening the bug 

Screenshot : 
![image](https://user-images.githubusercontent.com/102220709/228206994-d932e832-da94-4191-a9a8-62ee099bf7c3.png)

Tested on:

- Wallet Device:
Phone make/model: Apple iPhone 7
OS: iOS 15
BLE version : 4.2

- Verifier Device:
Phone make/model: Google Pixel 6
OS: Android 13
BLE version : 5.2

MOSIP Version : 1.2.0.1
MOSIP server : qa-1201-b2.net
APP link : https://github.com/mosip/inji/actions/runs/4511525622

**Comment by vharsh** [comment] 2023-04-03 10:36
@santhoshsunder Do you have logs from Android for the above failure?

**Comment by Kratitva** [comment] 2023-04-24 03:59
This issue is now tracked in JIRA: https://mosip.atlassian.net/browse/INJI-68

**Comment by santhoshsunder** [comment] 2023-11-28 12:35
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/102220709/134e7fe4-44dd-49c5-8079-6da5e2663a31)

**Closed by santhoshsunder** 2023-11-28 12:35 UTC
Labels: bug, triage, BLE, BLE-Sharing
