### ISSUE TITLE
Android - Specific devices are not connecting for sharing 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#523] opened 2023-02-01 10:33 UTC
**Describe the bug**
Specific devices are not connecting for sharing (device details are listed down below )

**To Reproduce**
Prerequiste: VC is downloaded and stored in sharing device
Device A - Requesting device
Device B - Sharing device

steps:

1. open qr code in Device A
2. open scanner in Device B

**Expected behavior**
The app should connect with eachother any devices and should able to share VC

**Observed**
When this specific devices as sender and receiver, it is not connecting at all, but its connecting and sharing VC if the device is inter changed their roles as sender and receiver

**Video**
https://user-images.githubusercontent.com/102220709/216018731-61b89331-7340-4ff1-92a2-e65d7e1fba34.mp4

**Smartphone :**

Sender device :
Android version : 12
BLE version : 5.0
device name : vivo Y73

Receiving device :
Android version : 11
BLE version : 5.0
device name : Redmi K20 Pro

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4123991786

**Comment by rakhimosip** [comment] 2023-02-01 10:43
Request to execute the same test case with the GNB sharing mechanism.

**Comment by santhoshsunder** [comment] 2023-02-13 10:55
I verified this issue in the new APK, the apk's link where listed below, the issue is still occurring with the same specific set of devices, but it's connecting and shares VC if the device is interchanged their roles as sender and receiver

**Smartphone :**

Sender device :
Android version : 12
BLE version : 5.0
device name : vivo Y73

Receiving device :
Android version : 11
BLE version : 5.0
device name : Redmi K20 Pro

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4123991786

**Comment by Alka1703** [comment] 2023-02-24 13:52
Please verify this on the latest build for the above mentioned combinations. 

PR for mosip/tuvali: https://github.com/mosip/tuvali/pull/26
PR for mosip/inji:https://github.com/mosip/inji/pull/584
The PRs have been merged in 24-02-2023 Release and the latest commit id on mosip/inji/develop is cb47493

If it is still reproducible, please attach the logs for both verifier and wallet.

**Comment by santhoshsunder** [comment] 2023-02-27 05:48
I verified this issue in the new APK, the apk's link where listed below, the issue is still occurring with the same specific set of devices, but it's connecting and shares VC if the device is interchanged their roles as sender and receiver

Screenshots : 
![image](https://user-images.githubusercontent.com/102220709/221484430-cfc36637-5d60-4f1e-820c-ba44e6888047.png)
https://user-images.githubusercontent.com/102220709/221484498-c2d4196c-fd2b-4be6-a738-e89d92bd3c2d.mp4

Smartphone :

Sender device :
Android version : 12
BLE version : 5.0
device name : vivo Y73

Receiving device :
Android version : 11
BLE version : 5.0
device name : Redmi K20 Pro

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4270036357

**Comment by lsivanand** [comment] 2023-02-27 06:46
Devices were given to Dev team for  quick analysis,,

**Comment by santhoshsunder** [comment] 2023-02-27 07:40
These specific two devices are not connecting at all, even if the roles were interchanged, attaching the details below 

screenshot :
![image](https://user-images.githubusercontent.com/102220709/221502435-75425e8d-14ba-49be-bb18-874f59faaab2.png)
https://user-images.githubusercontent.com/102220709/221502495-a3f66e26-15e5-42ff-8837-82beb2724cf0.mp4

Smartphone :

Sender device :
Android version :  10
BLE version : 5.0
device name : redmi note 10 lite

Receiving device :
Android version : 9
BLE version : 4.2
device name : Redmi 6A

Remaining details :
MOSIP Version: 1.2.0.1
MOSIP server: qa-1201-b2.net
APP link; https://github.com/mosip/inji/actions/runs/4270036357

**Comment by Sujithbn** [comment] 2023-03-15 10:01
@santhoshsunder : Please verify this in latest build.

**Comment by Raginikrishnamurthy** [comment] 2023-03-16 07:26
This is a recent issue which was analyzed by Ravi's team. @Sujithbn please get the root cause added if fixed. Else, get the issue fixed. Just by retesting without knowing what is causing the issue, we cannot close the bug.

**Comment by lsivanand** [comment] 2023-03-16 07:26
@krishnakumar4a4 any specific fix is addressing this as well.. Just trying to understand rational behind re-test

**Comment by krishnakumar4a4** [comment] 2023-03-16 10:50
> Please verify this on the latest build for the above mentioned combinations.
> 
> PR for mosip/tuvali: [mosip/tuvali#26](https://github.com/mosip/tuvali/pull/26) PR for mosip/inji:#584 The PRs have been merged in 24-02-2023 Release and the latest commit id on mosip/inji/develop is [cb47493](https://github.com/mosip/inji/commit/cb47493075b0ba2db5df74ce9f986cff4b6b6204)
> 
> If it is still reproducible, please attach the logs for both verifier and wallet.

@lsivanand @Raginikrishnamurthy Quoting earlier reply from dev team a few weeks ago.

In that release we have introduced dynamic MTU negotiation across android to android devices. We were hopeful it is gonna address the issue specific to this device combination.

As mentioned in that reply, we have requested for logs for checking this issue further which were not provided. It would have been helpful to look at logs when the app was in debug mode. Right now, We cannot evaluate a root cause with the available details on this issue, as it's only reproduced on a specific set of devices. 

Could you get the logs and bluetooth capture as well from both the android devices this time. So that we can have first level of analysis.

Here are steps to obtain bluetooth capture from Android devices: https://github.com/ravikp/tuvali/blob/develop/docs/ble-packet-capture-steps.md

**Comment by Raginikrishnamurthy** [comment] 2023-10-09 12:34
Issue verified and closed on jira https://mosip.atlassian.net/browse/INJI-39 , hence closing here on Github.

**Closed by Raginikrishnamurthy** 2023-10-09 12:34 UTC
Labels: bug, Critical, triaged, BLE, BLE-Sharing, HotFix, moved-to-jira
