### ISSUE TITLE
Though we are able to retrieve record from idrepo , while requesting Otp displayed "UIN not available in DB".

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#292] opened 2022-12-01 10:33 UTC
**Describe the bug**
Though we are able to retrieve record from idrepo , while requesting Otp it says "UIN not available in DB".

**To Reproduce**
1. Request Otp
 
**URL**: {{url}}/resident/v1/req/otp

**Request:**
{
  "id": "mosip.identity.otp.internal",
  "individualId": "8920857029",
  "metadata": {},
  "otpChannel": ["PHONE", "EMAIL"],
  "requestTime": "2022-12-01T09:18:47.077Z",
  "transactionID": "1234567890",
  "version": "1.0" 
} 

**Response**
{
    "id": "mosip.identity.otp.internal",
    "version": "1.0",
    "transactionID": "1234567890",
    "responseTime": "2022-12-01T09:19:05.952Z",
    "errors": [
        {
            "errorCode": "IDA-MLC-018",
            "errorMessage": "UIN not available in database"
        }
    ],
    "response": null,
    "metadata": null
}

**Current behavior**
while requesting Otp displayed "UIN not available in DB"

**Expected behavior**
Request Otp should be successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/79500509/205015954-135135dc-19c8-4e04-8dee-01b9509a099c.png)
![image](https://user-images.githubusercontent.com/79500509/205016039-ef3d3157-74f6-40bd-99bf-8ad2cd792788.png)

**Smartphone (please complete the following information):**

- Device: Android , iOS
- OS: 16.0.2
- Inji app version: 0.4.1 (4) --> Testflight
- MOSIP Version: 1.2.0.1
- MOSIP server: qa5.mosip.net

**Additional context**
UIN : 8920857029

**Comment by Anushree09-N** [comment] 2022-12-02 09:20
@Sujithbn @LoganathanSekar7627 The issue is not reproducible now, UIN's started working all of sudden this morning (was able to download credentials). As we are not sure on root cause we will keep ticket open and reduce the severity of the bug

**Comment by Sujithbn** [comment] 2023-04-03 10:35
@Anushree09-N Loganathan added the root cause, please reverify and confirm.

**Comment by Raginikrishnamurthy** [comment] 2023-11-21 14:01
verified as fixed in the build with commit id in the below screenshot.
![image](https://github.com/mosip/inji/assets/88436594/651ebbe6-46c7-4ec5-b8ce-f6f12695712b)

**Closed by Raginikrishnamurthy** 2023-11-21 14:01 UTC
Labels: bug, triage, Critical, beta_must_fix
