### ISSUE TITLE
IOS - Get UIN/VID button is not working 

### ISSUE THREAD

**Issue by santhoshsunder** [mosip/inji#636] opened 2023-03-13 09:51 UTC
**Describe the bug**
The get UIN/VID button is not working in the ios devices 

**To Reproduce**
1. Open the app and authenticate it
2. Go to the home screen
3. Click on the ADD ID button
4. Now select the get UIN/VID button
5. Enter the AID and click on 

**Expected behavior**
The button should be responsible and should able to generate UIN/VID using AID

**Actual behavior**
The Button is clickable, but not making any actions 

**Screenshots**
https://user-images.githubusercontent.com/102220709/224665938-8ca2bb81-2f95-4ed5-b5de-b03d6bd76fdb.MOV

**Smartphone :**
Device: Iphone 8
IOS version : IOS 16
BLE version : 5.0
Testflight : 0.4.1 (25) Qa-1201 purple theme
Mimoto version: 1.2.0.1
MOSIP Version: qa-1201-b2.mosip.net

**Comment by adityankannan-tw** [comment] 2023-03-24 09:09
This issue has been fixed in #185 .

**Comment by krishnakumar4a4** [comment] 2023-03-24 14:05
Please refer to #185 for root cause details. The fix is given as part of 24-03-2023 release.

INJI PR link: https://github.com/mosip/inji/pull/670
Tuvali PR link: https://github.com/mosip/tuvali/pull/49

**Comment by Anushree09-N** [comment] 2023-03-28 10:22
**Verified in :**
iphone 7 | iphone 15.6 BLE 4.2

 **app commit id:** 
![image](https://user-images.githubusercontent.com/79500509/228137632-f20d8a2d-c91c-4413-ad75-6dfb3b668541.png)

**iOS app version** :0.4.1 (32)

![IMG20230328110358](https://user-images.githubusercontent.com/79500509/228138150-3915086b-22e8-4564-8ca2-3edf54d4dc41.jpg)
 
Able to retrieve VID for the given application ID


https://user-images.githubusercontent.com/79500509/228206820-b5d952a2-d463-4019-a39e-122d86cb7e04.MP4

**Closed by Anushree09-N** 2023-03-28 10:22 UTC
Labels: bug, triage, blocker, BLE
