### ISSUE TITLE
Removed fullname attribute in policy and try to generate VC, for the name field in the app the value is blank but when we checked in All vid list--it displays undefined

### ISSUE THREAD

**Issue by Anushree09-N** [mosip/inji#91] opened 2022-09-05 03:18 UTC
**Describe the bug**
Removed fullname attribute in policy and try to generate VC, for the name field in the app the value is blank but when we checked in All vid list--it displays undefined

**To Reproduce**
1. Click “Add VID”
2. Enter correct UIN code and click “Generate VID” – should display screen to enter verification code
3. Enter correct verification code – should display “Downloading your VID”
4. Click “Back home” – should be taken back to page with generated VC or loading screen
5. Once available, click generated VC – should be taken to detailed view
6. clicked on Generated VC and check fullname lable-it should be in blank.                             
7. Go back to All Vid List and see fullname is displayed with undefined .

**Current behavior**
when we are in the home page the VC is named as undefined

**Expected behavior**
the name feild should be left empty in the home page 

**Screenshots**
![Image from iOS (1)](https://user-images.githubusercontent.com/79500509/188353542-b0a08d95-81f9-495e-8e45-e524c450db57.jpg)
![Image from iOS](https://user-images.githubusercontent.com/79500509/188353593-b1b03ec9-ee50-40c2-a990-8f7f59adff94.jpg)

**Smartphone (please complete the following information):**

- Device: Android
- Inji app version: [e.g 0.3.0]
- Mimoto version: [e.g 1.2.x]
- MOSIP Version: [e.g. 1.2.1]
- Mimoto server: [e.g. https://.....com]
- MOSIP server: [e.g. https://...mosip.com]

**Additional context**

**Comment by santhoshsunder** [comment] 2022-09-06 10:10
[Screenshot 2022-09-06 153806.pdf](https://github.com/mosip/inji/files/9495647/Screenshot.2022-09-06.153806.pdf)

**Comment by santhoshsunder** [comment] 2022-09-06 10:11
final comment by @rakhimosip : 
We can revisit based on the design that we adopt for UI and how resident attribute fields are mapped to VC

**Comment by Sujithbn** [comment] 2022-11-07 12:41
This needs to be rested after latest CSS changes

**Comment by santhoshsunder** [comment] 2022-11-16 11:49
Tested this issue in QA-121 env, the issue is not observed any more, hense closing this bug

**Closed by santhoshsunder** 2022-11-16 11:49 UTC
Labels: bug, triaged, Retest
